version: '3'

services:
  firefox:
    image: selenium/standalone-firefox-debug:3.14.0-curium
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - selenium

  app:
    build: .
    restart: on-failure
    image: 'webwhatsapi'
    container_name: "webwhatsapi_container"
    command:
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - ${API_PORT}:8000
    environment:
      - SELENIUM_SERVER_DEFAULT=http://firefox:4444/wd/hub
    volumes:
      - "./:/app"
    networks:
      - selenium
    extra_hosts:
      - "DOCKER_HOST_IP:${DOCKER_HOST_IP}"
    depends_on:
      - firefox



volumes:
  devshm:

networks:
  selenium:
